version: '3.8'
services:
  petal_poc_dev:
    container_name: petal_poc_dev 
    hostname: petal_poc_dev
    image: postgres:14.5-alpine

    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petal_poc_dev
    volumes:
      - ./Docker/data/funshopdb:/var/lib/postgresql/data/
